#:schema https://yazi-rs.github.io/schemas/yazi.json

[mgr]
linemode = 'mtime'

[opener]
edit = [
  { run = 'nvim %s', block = true },
]
convert_hevc = [
  { run = 'pwsh "E:\ps1\path\hevc.ps1" "-LiteralPath" "%s1"', block = true, desc = 'Convert to HEVC', for = 'windows' },
]

[open]
prepend_rules = [
  { mime = 'video/*', use = ['play', 'reveal', 'convert_hevc'] },
]
